### ISSUE TITLE
Consume webservice with other clients

### ISSUE THREAD

**Issue by po5i** [mikisvaz/simplews#1]
Is it possible to have a client different thant simplews? I have problems using savon or soap4r, both of them said that the operation is not supported.

The example with soap is the following:

```
client = Savon.client(wsdl: "/home/carlos/sandbox/simplews/hello.wsdl")

client.operations
=> [:hello, :wsdl, :documentation]


response = client.call(:hello)
I, [2013-07-19T15:51:07.874591 #8317]  INFO -- : SOAP request: http://localhost:1984
I, [2013-07-19T15:51:07.874859 #8317]  INFO -- : SOAPAction: "urn:SimpleWS#hello", Content-Type: text/xml;charset=UTF-8, Content-Length: 288
D, [2013-07-19T15:51:07.874984 #8317] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="SimpleWS-NS" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><tns:hello></tns:hello></env:Body></env:Envelope>
D, [2013-07-19T15:51:07.875671 #8317] DEBUG -- : HTTPI POST request to localhost (httpclient)
I, [2013-07-19T15:51:07.885947 #8317]  INFO -- : SOAP response (status 500)
D, [2013-07-19T15:51:07.886225 #8317] DEBUG -- : <?xml version="1.0" encoding="utf-8" ?>
<env:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Body>
    <env:Fault xmlns:n1="http://schemas.xmlsoap.org/soap/encoding/"
        env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
      <faultcode>env:Server</faultcode>
      <faultstring xsi:type="xsd:string">operation: urn:SimpleWS#hello {SimpleWS-NS}hello not supported</faultstring>
      <faultactor xsi:type="xsd:string">Web Server for SimpleWS</faultactor>
      <detail xsi:type="xsd:string">failed to serialize detail object: undefined method `sub&apos; for :@excn_type_name:Symbol</detail>
    </env:Fault>
  </env:Body>
</env:Envelope>
Savon::SOAPFault: (env:Server) operation: urn:SimpleWS#hello {SimpleWS-NS}hello not supported
    from /var/lib/gems/1.9.1/gems/savon-2.2.0/lib/savon/response.rb:70:in `raise_soap_and_http_errors!'
    from /var/lib/gems/1.9.1/gems/savon-2.2.0/lib/savon/response.rb:13:in `initialize'
    from /var/lib/gems/1.9.1/gems/savon-2.2.0/lib/savon/operation.rb:53:in `new'
    from /var/lib/gems/1.9.1/gems/savon-2.2.0/lib/savon/operation.rb:53:in `call'
    from /var/lib/gems/1.9.1/gems/savon-2.2.0/lib/savon/client.rb:36:in `call'
    from (irb):127
    from /usr/bin/irb:12:in `<main>'

```

The WS is the first example hello_world

```
serve :hello do 
  "Hello world!"
end
```

**Comment by mikisvaz** [comment]
Dear po5i,

Sorry for the late reply, I'm not maintaining this gem much anymore and I don't pay much attention to issues in github anyway. Since the details of SOAP escape me, added to my aversion to XML, I really don't know what that means. 

If I have time I'll take a look at it.

Sorry for the late and disappointing reply
